version: '2'
services:
  php:
    build:
      context: ./php
    container_name: php-apache
    volumes:
      - ./src:/var/www/html
    ports:
      - "8000:80"
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    container_name: mysqlHost
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=laravel
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    container_name: phpmyadmin
    environment:
       PMA_HOST: mysql
       MYSQl_ROOT_PASSWORD : 
    ports:
      - "8080:80"

volumes:
  mysql-data:
